yatube/about/urls.py
# about/urls.py
from django.urls import path

from . import views

app_name = 'about_namespace'

urlpatterns = [
    # Если из views подтягиваем класс,
    # то нужно использовать метод as_view()
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

# Позволяет обращаться к файлам дирректории в MEDIA_ROOT
# по имени, через префикс MEDIA_URL
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/urls.py
# Импортируем из приложения django.contrib.auth.views
# нужные обработчики/ view-класс
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeView, PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'  # Указываем namespace

urlpatterns = [
    # Представление, основанное на классе. В path()
    # view-классы вызываются через метод :
    # path('any_url/', ClassName.as_view())
    # В as_view() можно прямо дать ссылку на шаблон
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    # Полный адрес страницы регистрации - auth/signup/,
    # но префикс auth/ обрабатывется в головном urls.py
    path('signup/', views.SignUp.as_view(), name='var_signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='var_login'),
    path('password_reset/', PasswordResetView.as_view(),
         name='var_password_reset_form'),
    path('password_change/', PasswordChangeView.as_view(),
         name='var_password_change'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
# По умолчанию в проект Django подключена система администрирования
from django.contrib import admin
# Функция include позволит использовать path() из других файлов.
from django.urls import include, path

# Каким view обрабатывать ошибки
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    # Если на сервер пришел запрос '', только для namespace 'posts'
    # перейди в urls приложения posts и проверь там все path()
    # на совпадения с запрошенный url
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),

    # Все адреса с префиксом auth/ будут перенаправлены
    # в приложение users файл users/urls,
    # и там уже указывать auth/ в ссылке не нужно
    path('auth/', include('users.urls')),

    # Все что не проматчилось выше в  'users/urls'
    # попадет в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),

    path('about/', include('about.urls', namespace='about_namespace')),
]

# В режиме отлажки позволяет обращаться к файлам в директории,
# указанной в MEDIA_ROOT по имени, через префикс MEDIA_URL.
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ key_year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer> 

yatube/templates/includes/header.html
{% load static %}

<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    {% with request.resolver_match.view_name as view_short_name %}  
    <ul class="nav nav-pills">
      <li class="nav-item"> 
        <a class="nav-link {% if view_short_name  == 'about_namespace:author' %}active{% endif %}" href="{% url 'about_namespace:author' %}">Об авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_short_name  == 'about_namespace:tech' %}active{% endif %}" href="{% url 'about_namespace:tech' %}">Технологии</a>
      </li>
      {% if user.username  %}
      <li class="nav-item"> 
        <a class="nav-link {% if view_short_name  == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:var_password_change' %}">Изменить пароль</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_short_name == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
      </li>
      <li>
        Пользователь: {{ user.username }}
      </li>
      {% else %}
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_short_name  == 'users:var_login' %}active{% endif %}" href="{% url 'users:var_login' %}">Войти</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_short_name  == 'users:var_signup' %}active{% endif %}" href="{% url 'users:var_signup' %}">Регистрация</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endwith %} 