yatube/about/urls.py
# about/urls.py
from django.urls import path

from . import views

app_name = 'about_namespace'

urlpatterns = [
    # Если из views подтягиваем класс,
    # то нужно использовать метод as_view()
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/users/urls.py
# Импортируем из приложения django.contrib.auth.views
# нужные обработчики/ view-класс
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeView, PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'  # Указываем namespace

urlpatterns = [
    # Представление, основанное на классе. В path()
    # view-классы вызываются через метод :
    # path('any_url/', ClassName.as_view())
    # В as_view() можно прямо дать ссылку на шаблон
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    # Полный адрес страницы регистрации - auth/signup/,
    # но префикс auth/ обрабатывется в головном urls.py
    path('signup/', views.SignUp.as_view(), name='var_signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='var_login'),
    path('password_reset/', PasswordResetView.as_view(),
         name='var_password_reset_form'),
    path('password_change/', PasswordChangeView.as_view(),
         name='var_password_change'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
# По умолчанию в проект Django подключена система администрирования
from django.contrib import admin
# Функция include позволит использовать path() из других файлов.
from django.urls import include, path

# Каким view обрабатывать ошибки
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    # Если на сервер пришел запрос '', только для namespace 'posts'
    # перейди в urls приложения posts и проверь там все path()
    # на совпадения с запрошенный url
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),

    # Все адреса с префиксом auth/ будут перенаправлены
    # в приложение users файл users/urls,
    # и там уже указывать auth/ в ссылке не нужно
    path('auth/', include('users.urls')),

    # Все что не проматчилось выше в  'users/urls'
    # попадет в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),

    path('about/', include('about.urls', namespace='about_namespace')),
]

# В режиме отлажки позволяет обращаться к файлам в директории,
# указанной в MEDIA_ROOT по имени, через префикс MEDIA_URL.
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/models.py
# from django.db import models

# Create your models here.

yatube/users/forms.py
# Формы принято хранить в отдельном файле.
# К формам обращаемся из views.py

from django.contrib.auth import get_user_model
# UserCreationForm встроенный класс, наследник forms.ModelForm
# UserCreationForm был создан (не мной) на основе модели User
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


# Создаем свой класс для регистрации CreationForm
class CreationForm(UserCreationForm):
    # Наследуется класс Meta, вложенный в класс UserCreationForm
    # что бы унаследовать ключи и переопределить их
    class Meta(UserCreationForm.Meta):
        # На основе модели models.py User создаем класс формы
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
"""Что тут происходит?
В шаблон users/signup.html будет отправлена форма с полями,
описанными в классе CreationForm. После заполнения этой формы
пользователь будет переадресован на страницу, для которой в urls.py
указано имя name='posts:index'. Данные, отправленные через форму,
будут переданы в модель User и сохранены в БД.
"""

# Функция reverse_lazy позволяет получить URL по параметрам функции path()
from django.urls import reverse_lazy
from django.views.generic import CreateView

# Импортируем класс формы, что бы сослаться на неё во view-классе
from .forms import CreationForm


class SignUp(CreateView):
    # Создаем объект формы
    form_class = CreationForm
    # success_url - URL-адрес для перенаправления
    # после успешной обработки формы.
    # Так и не понял зачем нужен reverse_lazy
    success_url = reverse_lazy('posts:index')

    # template_name — имя шаблона, куда будет передана переменная form
    template_name = 'users/signup.html'

# Отсальные пути обрабатываются стандартным обработчиком,
# см. users/urls.py

yatube/templates/users/logged_out.html
{# Это код файла templates/users/logged_out.html #}

{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}{# base.html подтягивает блок content от сюда #}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
# templates/users/login.html

{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:var_password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/signup.html
<!-- templates/users/signup.html -->
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}{# base.html подтягивает блок content от сюда #}
  <div class="row justify-content-center">
    <div class="col-md-4 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {# Этот блок будет показан, если в форме есть ошибки #}
          {% load user_filters %} {# Подгружаем фильры из файла core/temlatetags/user_filters #}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

            <form method="post" action="{% url 'users:var_signup' %}">
              {% csrf_token %}
              {% for field in form %}{# View-класс передаёт в form объект формы. Объект form содержит список полей веб-формы. #}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field|addclass:'form-control' }} {# К полю ввода добавляем атрибут class. #}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}